import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/core/Navbar";
import Footer from "./components/core/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NeuroDevs - Software Agency",
  description: "Generated by Jannatul Lima",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body

        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <div className="min-h-screen pt-18">{children}</div>
        <Footer />

      </body>
    </html>
  );
}
